# Linear Algebra

In [1]:
import numpy as np

In [2]:
# Don't use np.matrix, use darray

In [3]:
mtr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
mtr2 = np.array([[5,4,3],[2,5,6],[-5,6,11]])
print(mtr1)
print(mtr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 5  4  3]
 [ 2  5  6]
 [-5  6 11]]


In [4]:
mtr1.dot(mtr2)  # dot product

array([[ -6,  32,  48],
       [  0,  77, 108],
       [  6, 122, 168]])

In [5]:
mtr1*mtr2  # cross product

array([[  5,   8,   9],
       [  8,  25,  36],
       [-35,  48,  99]])

In [6]:
np.outer(mtr1, mtr2)  # outer product https://math.stackexchange.com/questions/973559/outer-product-of-two-matrices/1507752

array([[  5,   4,   3,   2,   5,   6,  -5,   6,  11],
       [ 10,   8,   6,   4,  10,  12, -10,  12,  22],
       [ 15,  12,   9,   6,  15,  18, -15,  18,  33],
       [ 20,  16,  12,   8,  20,  24, -20,  24,  44],
       [ 25,  20,  15,  10,  25,  30, -25,  30,  55],
       [ 30,  24,  18,  12,  30,  36, -30,  36,  66],
       [ 35,  28,  21,  14,  35,  42, -35,  42,  77],
       [ 40,  32,  24,  16,  40,  48, -40,  48,  88],
       [ 45,  36,  27,  18,  45,  54, -45,  54,  99]])

In [7]:
np.inner(mtr1, mtr2)  # Inner product

array([[ 22,  30,  40],
       [ 58,  69,  76],
       [ 94, 108, 112]])

In [9]:
np.linalg.eig(mtr1)  # eigenvalue of the matrix

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [16]:
import scipy.linalg

In [17]:
scipy.linalg.eig(mtr1)

(array([ 1.61168440e+01+0.j, -1.11684397e+00+0.j, -1.30367773e-15+0.j]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [18]:
import scipy.sparse

In [22]:
spr = scipy.sparse.csr_matrix([[1,0,0],[0,1,0],[0,0,1]])  # Identity matrix
spr

<3x3 sparse matrix of type '<class 'numpy.intc'>'
	with 3 stored elements in Compressed Sparse Row format>