# Mathematical Functions Lecture

In [2]:
import numpy as np

In [3]:
arr = np.arange(-50, 100)
arr

array([-50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38,
       -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27, -26, -25,
       -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14, -13, -12,
       -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,
         2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99])

In [4]:
np.absolute(arr)  # Absolute value of everything inside the array

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0,
        1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
np.sqrt(arr)

<ipython-input-5-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
       0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897

In [6]:
np.log(arr)  # Natural log

<ipython-input-6-9e6f6b05ca06>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)  # Natural log
<ipython-input-6-9e6f6b05ca06>:1: RuntimeWarning: invalid value encountered in log
  np.log(arr)  # Natural log


array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
             -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805

In [7]:
np.log10(arr)  # Log base 10

<ipython-input-7-3b245c0c45d4>:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)  # Log base 10
<ipython-input-7-3b245c0c45d4>:1: RuntimeWarning: invalid value encountered in log10
  np.log10(arr)  # Log base 10


array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
             -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251,
       1.        , 1.04139269, 1.07918125, 1.11394335, 1.14612804,
       1.17609126, 1.20411998, 1.23044892, 1.25527251, 1.2787536 ,
       1.30103   , 1.32221929, 1.34242268, 1.36172784, 1.38021

In [8]:
np.exp(arr)  # e to the power of everything in the array

array([1.92874985e-22, 5.24288566e-22, 1.42516408e-21, 3.87399763e-21,
       1.05306174e-20, 2.86251858e-20, 7.78113224e-20, 2.11513104e-19,
       5.74952226e-19, 1.56288219e-18, 4.24835426e-18, 1.15482242e-17,
       3.13913279e-17, 8.53304763e-17, 2.31952283e-16, 6.30511676e-16,
       1.71390843e-15, 4.65888615e-15, 1.26641655e-14, 3.44247711e-14,
       9.35762297e-14, 2.54366565e-13, 6.91440011e-13, 1.87952882e-12,
       5.10908903e-12, 1.38879439e-11, 3.77513454e-11, 1.02618796e-10,
       2.78946809e-10, 7.58256043e-10, 2.06115362e-09, 5.60279644e-09,
       1.52299797e-08, 4.13993772e-08, 1.12535175e-07, 3.05902321e-07,
       8.31528719e-07, 2.26032941e-06, 6.14421235e-06, 1.67017008e-05,
       4.53999298e-05, 1.23409804e-04, 3.35462628e-04, 9.11881966e-04,
       2.47875218e-03, 6.73794700e-03, 1.83156389e-02, 4.97870684e-02,
       1.35335283e-01, 3.67879441e-01, 1.00000000e+00, 2.71828183e+00,
       7.38905610e+00, 2.00855369e+01, 5.45981500e+01, 1.48413159e+02,
      

# Statistical methods in NumPy

In [10]:
np.percentile(arr, 5)  # The 5th percentile

-42.55

In [11]:
np.percentile(arr, 50)  # The median

24.5

In [12]:
np.median(arr)  # The median

24.5

In [13]:
np.mean(arr)  # The mean, straight average

24.5

In [14]:
np.average(arr)  # The mean, can do weighted average

24.5

In [15]:
arr2 = np.arange(1, 6)
weights = np.array([.1, .3, .1, .2, .3])  # Weights have to add up to 1

In [16]:
np.average(arr2, weights=weights)

3.3

In [17]:
np.var(arr2)  # Variance

2.0

In [18]:
np.std(arr2)  # Standard deviation

1.4142135623730951

In [19]:
np.random.random(100)

array([0.31533357, 0.6042072 , 0.09254975, 0.04324346, 0.46775567,
       0.27858424, 0.80885404, 0.40244882, 0.69843475, 0.86585569,
       0.83469379, 0.11932477, 0.42751115, 0.2165859 , 0.70245569,
       0.1137281 , 0.94921778, 0.43937295, 0.84250483, 0.99274838,
       0.5624569 , 0.567934  , 0.93966437, 0.84578608, 0.38163937,
       0.13895859, 0.20186786, 0.69744426, 0.79927422, 0.66939382,
       0.85285189, 0.56402934, 0.70468197, 0.15007611, 0.26167309,
       0.44685982, 0.35218762, 0.50074012, 0.52622171, 0.42080004,
       0.93631003, 0.92513224, 0.83314852, 0.36939337, 0.38345143,
       0.77448425, 0.19832687, 0.06994646, 0.01014197, 0.68295689,
       0.87298924, 0.3872399 , 0.93588138, 0.52057969, 0.58367805,
       0.43817157, 0.08708873, 0.38459559, 0.60646481, 0.83252898,
       0.44546613, 0.79373079, 0.61011463, 0.27973477, 0.58106482,
       0.0966082 , 0.67022385, 0.55266177, 0.84429837, 0.30306762,
       0.46129835, 0.58610136, 0.20097598, 0.01306987, 0.17495

In [20]:
np.random.randint(1, 100, 100)

array([58, 97, 28, 35, 78, 35, 24, 56, 71, 54, 59,  1, 38, 26, 84, 39, 87,
       69, 10, 87, 39, 84, 23, 94, 52, 32, 63, 46, 40, 15,  3, 39,  7,  9,
       27, 29, 59, 70, 62, 89, 84, 50, 11, 75, 25, 55, 24, 40, 77, 46, 91,
       27,  2, 44, 27, 54, 72, 48, 80,  9, 92, 52,  4, 97, 60, 39, 48,  5,
       15, 50, 25, 87, 76, 17, 68, 61, 77, 44, 91, 57, 47, 83, 53, 66, 49,
       26, 59, 48, 59, 95, 81, 82, 29, 72,  3, 24, 12, 25, 26, 85])

In [21]:
arr2

array([1, 2, 3, 4, 5])

In [22]:
np.random.shuffle(arr2)  # Shuffle arr2, do not return a new array

In [23]:
np.random.permutation(arr2)   # Random permutation of arr2, return a new array

array([4, 1, 5, 3, 2])

In [24]:
np.random.choice(arr2, 2)  # A random choice with replacement (draw the number and put it back in to draw again) from arr2

array([3, 1])

In [25]:
np.random.choice(arr2, 10, p=weights)  # For each item in the array, use the weight as probability to be chosen

array([1, 1, 3, 1, 3, 1, 4, 1, 4, 4])

In [26]:
np.random.poisson(.3, 100)  # Draw 100 values from a Poisson distribution with lambda = .3

array([0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 4, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 2, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0])