# NumPy/SciPy

## Financial Functions

### Exercise 7
We already used numpy-financial in the midterm project; specifically, the IRR function. We had directly implemented the following formulas in the project. NumPy-Financial gives us some
canned functionality to do the same. Create a program that does the following:  
a. Computes the present value for a given rate, number of periods, and monthly payment.  
b. Calculates the monthly payment for a given rate, number of periods, and present value.  
c. Calculates the number of periods for a given rate, payment, and present value.  
d. Calculates the rate for a given number of periods, monthly payment, and present value.  

In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

#### a. Covariance Matrix

In [2]:
import numpy as np
import yfinance as yf

# Import data
de = yf.Ticker("DE")
cat = yf.Ticker("CAT")
coop = yf.Ticker("COOP")
dkng = yf.Ticker("DKNG")
wkhs = yf.Ticker("WKHS")
msft = yf.Ticker("MSFT")
nke = yf.Ticker("NKE")
dis = yf.Ticker("DIS")
shop = yf.Ticker("SHOP")
amzn = yf.Ticker("AMZN")

# Get DF
deData = de.history(period="max")
catData = cat.history(period="max")
coopData = coop.history(period="max")
dkngData = dkng.history(period="max")
wkhsData = wkhs.history(period="max")
msftData = msft.history(period="max")
nkeData = nke.history(period="max")
disData = dis.history(period="max")
shopData = shop.history(period="max")
amznData = amzn.history(period="max")

# Get 10 last close price of 10 stocks
lastclosePrice = np.array([deData.Close[-10:], 
                           catData.Close[-10:], 
                           coopData.Close[-10:], 
                           dkngData.Close[-10:], 
                           wkhsData.Close[-10:], 
                           msftData.Close[-10:], 
                           nkeData.Close[-10:], 
                           disData.Close[-10:], 
                           shopData.Close[-10:], 
                           amznData.Close[-10:]])

# Covariance matrix
covarianceMatrix = np.cov(lastclosePrice, rowvar=False)
covarianceMatrix

array([[ 978396.27442047,  948030.15976682,  978017.78910169,
         976134.6130384 , 1005839.51917642, 1051587.97711012,
        1052699.25656086, 1027804.4392378 , 1020153.99951666,
         999744.11665885],
       [ 948030.15976682,  918616.64234922,  947675.55124589,
         945851.7525483 ,  974629.55367557, 1018913.45492026,
        1020002.00842917,  995885.51129463,  988477.60853321,
         968711.35729597],
       [ 978017.78910169,  947675.55124589,  977655.5769476 ,
         975774.20387904, 1005463.71407291, 1051140.76360185,
        1052265.22750456, 1027386.60161021, 1019745.87416199,
         999355.52344939],
       [ 976134.6130384 ,  945851.7525483 ,  975774.20387904,
         973899.95397409, 1003531.86257317, 1049133.84662388,
        1050251.79281634, 1025425.03763044, 1017799.35705895,
         997449.04850947],
       [1005839.51917642,  974629.55367557, 1005463.71407291,
        1003531.86257317, 1034072.12352302, 1081086.7879902 ,
        1082231.10602646

#### b. Correlated array of random numbers using numpy.random.multivariate_normal

In [3]:
means = np.array(list(map(np.mean, lastclosePrice)))  # Calculate means closing price of each stocks, pass to a list then convert to an array
np.reshape(means, (10,1))  # Resize to a 10x1 matrix
m = np.random.multivariate_normal(means, covarianceMatrix, 10)
m

array([[ 234.3210022 ],
       [ 159.75200043],
       [  23.90400009],
       [  50.92900009],
       [  24.13299999],
       [ 215.69500122],
       [ 128.96300125],
       [ 124.99700089],
       [1076.96400146],
       [3283.36794434]])

array([[  -91.46002984,  -148.37278718,  -290.09458622,  -265.39826212,
         -304.00894577,  -187.39877472,  -255.98259837,  -250.42635973,
          710.89361937,  2934.91634361],
       [  122.94638766,    50.69885756,   -89.4437389 ,   -62.40038579,
          -91.4776327 ,    98.61205786,     9.71908805,     8.23816154,
          959.19032158,  3168.56845095],
       [ -740.20743586,  -786.75271052,  -952.28838216,  -925.27205877,
         -979.49478716,  -830.61403781,  -920.52615783,  -903.71389685,
           53.07051982,  2274.13387687],
       [ -500.49158602,  -551.94500878,  -710.39512234,  -678.58215558,
         -727.73084229,  -559.71758711,  -650.83397334,  -632.32641375,
          324.84874111,  2548.63434916],
       [ -779.75032369,  -821.88708011,  -988.3445043 ,  -956.96203414,
        -1014.68389173,  -863.70121234,  -955.38349701,  -931.11329469,
           28.05098477,  2255.18185689],
       [   12.00039581,   -52.34867443,  -194.30316507,  -167.08014396,
   

#### c. Correlated array of random numbers using numpy.random.standard_normal

In [6]:
# Create array of uncorrelated random numbers in the form of a 10x10 matrix
uncorr = np.reshape(np.random.standard_normal(100), (10,10))

# Choleskyu decomposition
L = np.linalg.cholesky(covarianceMatrix)

# Correlated array of random numbers
corr = np.dot(L, uncorr)
corr

array([[ -687.44333637,  1642.61254497,  -159.45575742,    94.60983852,
        -1201.85150892,   352.19673633, -1502.56716494,  -757.54963387,
          233.24874768,  -588.09316341],
       [ -664.48750187,  1589.58582631,  -159.47355655,    89.97082724,
        -1161.83324355,   342.01272627, -1451.58744298,  -735.9686861 ,
          224.2518979 ,  -571.08517431],
       [ -685.06788124,  1640.53911185,  -166.93490285,    93.87899059,
        -1197.71590807,   351.46497828, -1495.3615015 ,  -759.24206734,
          231.15414814,  -591.39701653],
       [ -686.21220786,  1637.20710526,  -168.50974944,    94.64881579,
        -1193.1856434 ,   352.53946443, -1492.8631962 ,  -754.85053677,
          231.67557214,  -591.43029172],
       [ -708.94992367,  1687.9598434 ,  -172.46498573,   100.18055809,
        -1229.32135996,   360.97200553, -1538.20202102,  -775.93458608,
          239.21021259,  -610.99474887],
       [ -765.50624407,  1766.82349946,  -162.79789673,   116.8876149 ,
   