# NumPy/SciPy

## Matrices

### Exercise 4
Create two 5x5 matrices of numbers:  
a. Multiply both matrices together.  
b. Compute the eigenvalues of the matrices.  
c. Calculate the correlation matrix for each of the two matrices.  

In [1]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np

# Create NDarrays containing 25 random number
arr1 = np.random.random(25)
arr2 = np.random.random(25)

# Create matrix from previous NDarrays, resize to 5x5 matrix
mat1 = np.resize(np.array(arr1), (5,5))
mat2 = np.resize(np.array(arr2), (5,5))
mat1
mat2

array([[0.31658903, 0.47644279, 0.55709526, 0.4125317 , 0.72863083],
       [0.51895812, 0.46937613, 0.35517957, 0.18043565, 0.601927  ],
       [0.8386642 , 0.67422248, 0.53611114, 0.02133359, 0.46215097],
       [0.42137468, 0.66661297, 0.41953964, 0.02931688, 0.93308606],
       [0.79595656, 0.43531227, 0.92361037, 0.33163611, 0.42292978]])

array([[0.79269821, 0.06577914, 0.62517778, 0.40439582, 0.20851715],
       [0.5010884 , 0.71673801, 0.87165723, 0.47381074, 0.38957224],
       [0.13594098, 0.96721608, 0.90394815, 0.17826088, 0.58893569],
       [0.32045446, 0.36359944, 0.85323224, 0.25475374, 0.49246544],
       [0.72906287, 0.60495509, 0.02386641, 0.62535296, 0.9157217 ]])

#### a. Multiply both matrices together.

In [5]:
# Matrix multiplication
np.matmul(mat1, mat2)

array([[1.2288469 , 1.49192633, 1.48617961, 1.01382472, 1.45009708],
       [1.1915236 , 1.14383682, 1.22295944, 0.91795805, 1.14030144],
       [1.4193057 , 1.34428026, 1.62585418, 1.04861607, 1.18697694],
       [1.41476074, 1.48642476, 1.2710177 , 1.15201476, 1.46352433],
       [1.38925645, 1.63412921, 2.00500976, 1.04174666, 1.43010859]])

#### b. Compute the eigenvalues of the matrices.

In [4]:
# Compute eigenvalues
np.linalg.eig(mat1)
np.linalg.eig(mat2)

(array([ 2.51983607+0.j        , -0.08437646+0.20737536j,
        -0.08437646-0.20737536j, -0.37238553+0.j        ,
        -0.20437466+0.j        ]),
 array([[-0.44681662+0.j        , -0.43103688+0.02623123j,
         -0.43103688-0.02623123j,  0.38046448+0.j        ,
          0.65151068+0.j        ],
        [-0.37948388+0.j        ,  0.02268646+0.41606467j,
          0.02268646-0.41606467j, -0.27607916+0.j        ,
         -0.47278939+0.j        ],
        [-0.44226487+0.j        ,  0.59742115+0.j        ,
          0.59742115-0.j        , -0.37072753+0.j        ,
         -0.49074543+0.j        ],
        [-0.44402417+0.j        , -0.3632183 -0.04356725j,
         -0.3632183 +0.04356725j, -0.6478637 +0.j        ,
         -0.14462834+0.j        ],
        [-0.51341135+0.j        , -0.036231  -0.38450526j,
         -0.036231  +0.38450526j,  0.47102102+0.j        ,
          0.30042568+0.j        ]]))

(array([2.64394752+0.j        , 0.06966483+0.33562035j,
        0.06966483-0.33562035j, 0.49173908+0.j        ,
        0.30884355+0.j        ]),
 array([[-3.28936644e-01+0.j        , -2.09397145e-01+0.36680139j,
         -2.09397145e-01-0.36680139j,  2.27757521e-01+0.j        ,
          5.22125330e-01+0.j        ],
        [-5.07290133e-01+0.j        , -2.19348564e-01+0.31122908j,
         -2.19348564e-01-0.31122908j,  4.20606794e-01+0.j        ,
          3.98793616e-01+0.j        ],
        [-5.06801739e-01+0.j        ,  7.86306444e-02-0.29996259j,
          7.86306444e-02+0.29996259j,  1.96688188e-01+0.j        ,
         -2.90519276e-04+0.j        ],
        [-3.98694094e-01+0.j        , -3.04871375e-01-0.41649794j,
         -3.04871375e-01+0.41649794j, -1.03940903e-01+0.j        ,
         -3.42964473e-01+0.j        ],
        [-4.67602846e-01+0.j        ,  5.60405945e-01+0.j        ,
          5.60405945e-01-0.j        , -8.49544867e-01+0.j        ,
         -6.71359872e-01+0.j

#### c. Calculate the correlation matrix for each of the two matrices.

In [6]:
np.corrcoef(mat1,mat2)

array([[ 1.00000000e+00,  3.88163875e-01, -1.61276439e-01,
         6.98196726e-01, -1.88981496e-01, -5.15144011e-01,
        -5.05813248e-02,  5.24176395e-01,  5.09492222e-01,
         6.28374189e-02],
       [ 3.88163875e-01,  1.00000000e+00,  7.34890716e-01,
         9.01001317e-01,  1.33952748e-01, -1.47770120e-01,
        -2.27399152e-01,  2.06404155e-01,  7.13527395e-02,
         4.68057621e-01],
       [-1.61276439e-01,  7.34890716e-01,  1.00000000e+00,
         5.07023835e-01,  5.78302505e-01,  2.40241468e-01,
         2.68639842e-01,  2.53490371e-01,  1.61792043e-01,
         8.24916283e-04],
       [ 6.98196726e-01,  9.01001317e-01,  5.07023835e-01,
         1.00000000e+00, -5.66410582e-02, -4.75848918e-01,
        -1.00355233e-01,  5.07096858e-01,  2.31453098e-01,
         3.59790705e-01],
       [-1.88981496e-01,  1.33952748e-01,  5.78302505e-01,
        -5.66410582e-02,  1.00000000e+00,  7.74142300e-01,
         5.78718775e-01,  1.42352235e-01,  6.64086074e-01,
        -6.